export const ROUTES = {
  workspaceRoot: '/workspace',
  home: '/workspace',
  acesso: '/workspace/acesso',
  acessoEmpresa: (slug: string) => `/workspace/acesso/${encodeURIComponent(slug)}`,
  convite: '/workspace/convite',
  ordens: '/workspace/ordens',
  novaOrdem: '/workspace/ordens/nova',
  ativos: '/workspace/ativos',
  novoAtivo: '/workspace/ativos/novo',
  admin: '/workspace/admin',
  configuracoes: '/workspace/configuracoes',
  perfil: '/workspace/perfil',
  pecas: '/workspace/pecas',
}
